jwt:
  secret: helloworldtest123456789!@#$%

smtp:
  host: smtp.naver.com
  email: spok_nb@naver.com
  password:
  port: 465

proxyServer:
  sites-enabled: C:\Users\joyou\Desktop

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #