
smtp:
  host: smtp.naver.com
  email: spok_nb@naver.com
  password: #
  port: 465

proxyServer:
  sites-enabled: C:\Users\joyou\Desktop

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    #내부용
#    url: jdbc:mysql://192.168.55.121:3306/orbit?serverTimezone=UTC&characterEncoding=UTF-8
#    #외부용
    url: jdbc:mysql://114.202.33.83:3306/orbit?serverTimezone=UTC&characterEncoding=UTF-8
    username: orbit
    password: #
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #

  profiles:
    active: jwt