spring:
  datasource:
    url: jdbc:mysql://114.202.33.83:3306/orbit?serverTimezone=UTC&characterEncoding=UTF-8
    username: orbit
    password: '!orbit1234@'
    driver-class-name: com.mysql.cj.jdbc.Driver